# Week 9: Exploratory Data Analysis HW

> Laiba Siddique

## Tasks

### Task 1: Determine the sample space elements, the frequency, and the relevant frequencies of the `diabetes` variable.

In [10]:
df.diabetes.unique()

array(['No', 'Yes'], dtype=object)

In [11]:
df.diabetes.value_counts()

diabetes
No     174
Yes    125
Name: count, dtype: int64

In [12]:
df.diabetes.value_counts(normalize=True)

diabetes
No     0.58194
Yes    0.41806
Name: proportion, dtype: float64

### Task 2: Determine the median `ejection_fraction` for each of the classes in the `anaemia` variable.

In [30]:
df.groupby('anaemia')['ejection_fraction'].median()

anaemia
No     38.0
Yes    38.0
Name: ejection_fraction, dtype: float64

### Task 3: Determine the variance in `ejection_fraction` for each of the classes in the `anaemia` variable.

In [37]:
df.groupby('anaemia').age.var(ddof=1)

anaemia
No     141.763348
Yes    139.675064
Name: age, dtype: float64

## Questions

### Question 1: How do you import the pandas package in Python?

See below. The `as pd` part is not required for importing pandas, though it makes working with it easier.

In [1]:
import pandas as pd

I will also import the stats module (as was done in the notes), just in case I need it.

In [9]:
from scipy import stats

### Question 2: What function do you use to read a CSV file in pandas?

Use `df = pd.read_csv('data.csv')`. The function is `.read_csv('csv_file_path.csv')` I have commnted this out below and imported a file using the raw method, so I actually have data to work with since I do not have the file downloaded and located in this repo.

In [6]:
# df = pd.read_csv('data.csv')
df = pd.read_csv('https://raw.githubusercontent.com/juanklopper/TutorialData/main/heart_failure.csv')

### Question 3: How do you display the first 5 rows of a DataFrame in pandas?

`df.head()` displays the first $5$ rows by default.

In [4]:
df.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,hypertension,platelets,serum_creatinine,serum_sodium,sex,smoking,time,death
0,75.0,No,582,No,20,Yes,265000.00,1.9,130,Male,No,4,Yes
1,55.0,No,7861,No,38,No,263358.03,1.1,136,Male,No,6,Yes
2,65.0,No,146,No,20,No,162000.00,1.3,129,Male,Yes,7,Yes
3,50.0,Yes,111,No,20,No,210000.00,1.9,137,Male,No,7,Yes
4,65.0,Yes,160,Yes,20,No,327000.00,2.7,116,Female,No,8,Yes

### Question 4: How do you calculate the mean of a column named `Age` in a DataFrame named `df`?

The mean for a numerical variable can be calculated using the `mean` method for a pandas series object. 
See below. In my dataset, `Age` is spelled as `age`.

In [15]:
# df['Age'].mean()
df['age'].mean()

np.float64(60.83389297658862)

### Question 5: How do you calculate the median of a column named `Salary` in a DataFrame named `df`?

The `median` method calculates the median of a pandas series object that contains numerical data
See below. The answer is commented out, so the output shows some other variable within my dataset instead (since it does not have a `Salary` colummn).

In [14]:
# df['Score'].median()
df['age'].median()

np.float64(60.0)

### Question 6: How do you calculate the standard deviation of a column named `Score` in a DataFrame named `df`?

See below. The answer is commented out, so the output shows some other variable within my dataset instead (since it does not have the specified columms).

In [33]:
# df.Score.std(ddof=1)
df.age.std(ddof=1)

np.float64(11.89480907404447)

### Question 7: How do you find the number of missing values in each column of a DataFrame named `df`?

Use `df.info()` to get the Non-Null count for each column. Subtract that value by the number of rows in the table for each column to find the number of missing values in each column. 
Alternatively, you can use `df.COLUMN_NAME.isna().sum()` where `COLUMN_NAME` is the name of the colomn to find the counts of each unique value, including count of missing values, for the specified column. You can do this for each column to find the number of missing values in each column.

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    object
 2   creatinine_phosphokinase  299 non-null    int64
 3   diabetes                  299 non-null    object
 4   ejection_fraction         299 non-null    int64
 5   hypertension              299 non-null    object
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64
 9   sex                       299 non-null    object
 10  smoking                   299 non-null    object
 11  time                      299 non-null    int64
 12  death                     299 non-null    object
dtypes: float64(3), int64(4), object(6)
memory usage: 30.5+ KB

In [27]:
# df.diabetes.value_counts(dropna=False) # another method, this ives more inforrmation. However, the below option gives specifically the number of missing values in the column.
df.diabetes.isna().sum()

np.int64(0)

### Question 8: How do you calculate the correlation between two columns, `Age` and `Salary`, in a DataFrame named `df`?

See below. The answer is commented out, so the output shows some other variable within my dataset instead (since it does not have the specified columms).

In [ ]:
# df.Age.corr(df['Salary'])
df.age.corr(df['ejection_fraction'])

np.float64(0.06009836323291279)

### Question 9: How do you select a subset of a DataFrame `df` where the column `Age` is greater than $30$?

See below. The answer is commented out, so the output shows some other variable within my dataset instead (since it does not have the specified columms).

In [36]:
# df[df.Age > 30]
df[df.age > 30]

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,hypertension,platelets,serum_creatinine,serum_sodium,sex,smoking,time,death
0,75.0,No,582,No,20,Yes,265000.00,1.9,130,Male,No,4,Yes
1,55.0,No,7861,No,38,No,263358.03,1.1,136,Male,No,6,Yes
2,65.0,No,146,No,20,No,162000.00,1.3,129,Male,Yes,7,Yes
3,50.0,Yes,111,No,20,No,210000.00,1.9,137,Male,No,7,Yes
4,65.0,Yes,160,Yes,20,No,327000.00,2.7,116,Female,No,8,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,No,61,Yes,38,Yes,155000.00,1.1,143,Male,Yes,270,No
295,55.0,No,1820,No,38,No,270000.00,1.2,139,Female,No,271,No
296,45.0,No,2060,Yes,60,No,742000.00,0.8,138,Female,No,278,No
297,45.0,No,2413,No,38,No,140000.00,1.4,140,Male,Yes,280,No
298,50.0,No,196,No,45,No,395000.00,1.6,136,Male,Yes,285,No

### Question 10: How do you calculate the range (maximum - minimum) of a column named `Score` in a DataFrame named `df`?

See below. The answer is commented out, so the output shows some other variable within my dataset instead (since it does not have the specified columms).

In [32]:
# df.Score.max() - df.Score.min()
df.age.max() - df.age.min()

np.float64(55.0)

### Question 11: How do you group a DataFrame `df` by a column named `Department` and calculate the mean of `Salary` within each group?

See below. The answer is commented out, so the output shows some other variable within my dataset instead (since it does not have the specified columms).

In [29]:
# df.groupby('Department').Salary.mean()
df.groupby('death').age.mean()

death
No     58.761906
Yes    65.215281
Name: age, dtype: float64

### Question 12: How do you group a DataFrame `df` by two columns, `Department` and `Job Title`, and count the number of rows within each group?

See below. The answer is commented out, so the output shows some other variable within my dataset instead (since it does not have the specified columms).

In [43]:
# df.groupby(['Department', 'Job Title']).size()
df.groupby(['diabetes', 'anaemia']).size()

diabetes  anaemia
No        No         98
          Yes        76
Yes       No         72
          Yes        53
dtype: int64

### Question 13: How do you use the `groupby` method to find the maximum `Age` in each `Department` in a DataFrame `df`?

See below. The answer is commented out, so the output shows some other variable within my dataset instead (since it does not have the specified columms).

In [39]:
# df.groupby('Department').age.max()
df.groupby('death').age.max()

death
No     90.0
Yes    95.0
Name: age, dtype: float64

### Question 14: How do you create a cross-tabulation table that shows the frequency count of `Department` (rows) and `Job Title` (columns) in a DataFrame `df`?

The pandas `crosstab` function can create a contingency table of the comparitive frequencies. The variable that is passed first, populates the rowss of the table.
See below. The answer is commented out, so the output shows some other variable within my dataset instead (since it does not have the specified columms).

In [21]:
# pd.crosstab(df.Department, df.Job_Title))
pd.crosstab(df.diabetes, df.anaemia)

anaemia   No  Yes
diabetes
No        98   76
Yes       72   53

### Question 15: How do you create a cross-tabulation table that shows the mean `Salary` for each combination of `Department` (rows) and `Job Title` (columns) in a DataFrame df?

See below. The answer is commented out, so the output shows some other variable within my dataset instead (since it does not have the specified columms).

In [23]:
# pd.crosstab(df.Department, df.Job_Title, df.Salary, aggfunc='mean')
pd.crosstab(df.diabetes, df.anaemia, df.age, aggfunc='mean')

anaemia          No        Yes
diabetes
No        60.428571  63.684211
Yes       59.236111  59.666679